Repository googleapis/python-aiplatform, pull requests merged in 2021-02, with the labels that each got.

#199 Fix: custom training jobs using managed non tabular dataset requiring annotation_schema_uri
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#169 feat: add async support to batch predict
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_models.py
Labels: cla: yes

#207 feat: Add accelerator options to Model/Endpoint deploy()
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/training_jobs.py
  google/cloud/aiplatform/utils.py
Labels: cla: yes

#211 fix: Add tests and final touches for PR #207
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/utils.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_utils.py
Labels: cla: yes

#198 feat: moves manual enhanced lib edits outside of generated files
  google/cloud/aiplatform/gapic/schema/__init__.py
  google/cloud/aiplatform/v1beta1/schema/predict/instance/__init__.py
  google/cloud/aiplatform/v1beta1/schema/predict/params/__init__.py
  google/cloud/aiplatform/v1beta1/schema/predict/prediction/__init__.py
  google/cloud/aiplatform/v1beta1/schema/trainingjob/definition/__init__.py
Labels: cla: yes

#204 feat: LRO metadata
  .sample_configs/process_configs.yaml
  samples/snippets/export_model_sample.py
  samples/snippets/export_model_tabular_classification_sample.py
  samples/snippets/export_model_tabular_classification_sample_test.py
  samples/snippets/export_model_video_action_recognition_sample.py
  samples/snippets/export_model_video_action_recognition_sample_test.py
Labels: cla: yes

#215 fix: Fix sample test
  samples/snippets/deploy_model_custom_trained_model_sample_test.py
Labels: cla: yes, samples

#222 fix: correct text sentiment analysis sample
  .sample_configs/param_handlers/create_training_pipeline_text_sentiment_analysis_sample.py
  samples/snippets/create_training_pipeline_text_sentiment_analysis_sample.py
Labels: cla: yes, samples

#225 chore: update sample configs to keep some samples in v1beta1
  .sample_configs/param_handlers/upload_model_explain_image_managed_container_sample.py
  .sample_configs/param_handlers/upload_model_explain_tabular_managed_container_sample.py
  .sample_configs/process_configs.yaml
  samples/snippets/conftest.py
Labels: cla: yes, samples

#221 chore: update prediction endpoint
  .sample_configs/process_configs.yaml
  samples/snippets/explain_tabular_sample.py
  samples/snippets/predict_custom_trained_model_sample.py
  samples/snippets/predict_image_classification_sample.py
  samples/snippets/predict_image_object_detection_sample.py
  samples/snippets/predict_sample.py
  samples/snippets/predict_tabular_classification_sample.py
  samples/snippets/predict_tabular_regression_sample.py
  samples/snippets/predict_text_classification_single_label_sample.py
  samples/snippets/predict_text_entity_extraction_sample.py
  samples/snippets/predict_text_sentiment_analysis_sample.py
Labels: cla: yes

#218 fix: rename schema.training_job.definition tabular_task to automl_tabular
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
Labels: cla: yes

#219 feat: Add SDK-wide delete method, cancel methods to Job and TrainingJob
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_lro.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#226 feat: exposes v1 enhanced types and adds tests
  google/cloud/aiplatform/gapic/schema/__init__.py
  google/cloud/aiplatform/v1/schema/__init__.py
  google/cloud/aiplatform/v1/schema/predict/__init__.py
  google/cloud/aiplatform/v1/schema/trainingjob/__init__.py
  tests/unit/enhanced_library/test_enhanced_types.py
Labels: cla: yes

#161 feat: Added CustomTrainingJob.get
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#239 fix: fix update export model sample, and add sample test
  .sample_configs/param_handlers/export_model_sample.py
  samples/snippets/export_model_sample.py
  samples/snippets/export_model_sample_test.py
Labels: api: aiplatform, cla: yes, samples

#220 feat: Added AutoMLTextTrainingJob and tests
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
Labels: cla: yes

#238 feat: Made get function available to all training jobs
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: api: aiplatform, cla: yes

#244 fix: fix create data labeling job samples tests
  samples/snippets/conftest.py
Labels: api: aiplatform, cla: yes, samples

#246 docs: update index.rst to include v1
  docs/index.rst
  google/cloud/aiplatform/__init__.py
Labels: api: aiplatform, cla: yes
