Repository googleapis/python-aiplatform, pull requests merged in 2021-03, with the labels that each got.

#250 fix: fix predict sample tests for proto-plus==1.14.2
  samples/snippets/predict_custom_trained_model_sample_test.py
  samples/snippets/predict_image_object_detection_sample_test.py
  samples/snippets/predict_tabular_classification_sample_test.py
Labels: api: aiplatform, cla: yes, samples

#235 feat: add automl video training class
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/constants.py
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
Labels: cla: yes

#252 chore: allow merge commits
  .github/sync-repo-settings.yaml
Labels: cla: yes

#254 fix: skip create data labeling job sample tests
  samples/snippets/create_data_labeling_job_active_learning_sample_test.py
  samples/snippets/create_data_labeling_job_image_segmentation_sample_test.py
  samples/snippets/create_data_labeling_job_images_sample_test.py
  samples/snippets/create_data_labeling_job_sample_test.py
  samples/snippets/create_data_labeling_job_specialist_pool_sample_test.py
  samples/snippets/create_data_labeling_job_video_sample_test.py
Labels: cla: yes, samples

#216 feat: Add Explanations to service APIs
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/explain/__init__.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_models.py
Labels: cla: yes

#256 feat: Added encryption_spec_key_name to all relevant resources
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
  google/cloud/aiplatform/initializer.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#262 chore: Modify integration tests to support VPC-SC environment
  tests/system/aiplatform/test_dataset.py
Labels: cla: yes

#267 fix: Fixed exception when the python executable path has a space in it
  google/cloud/aiplatform/training_jobs.py
Labels: cla: yes

#265 feat: Add initial Model Builder SDK samples
  samples/model-builder/conftest.py
  samples/model-builder/create_and_import_dataset_image_sample.py
  samples/model-builder/create_and_import_dataset_image_sample_test.py
  samples/model-builder/create_batch_prediction_job_sample.py
  samples/model-builder/create_batch_prediction_job_sample_test.py
  samples/model-builder/create_training_pipeline_image_classification_sample.py
  samples/model-builder/create_training_pipeline_image_classification_sample_test.py
  samples/model-builder/init_sample.py
  samples/model-builder/init_sample_test.py
  samples/model-builder/test_constants.py
Labels: api: aiplatform, cla: yes, samples

#277 feat: Add Custom Container Prediction support, move to single API endpoint
  google/cloud/aiplatform/initializer.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_initializer.py
  tests/unit/aiplatform/test_models.py
Labels: automerge, cla: yes
