Repository googleapis/python-aiplatform, pull requests merged in 2021-01, with the labels that each got.

#126 test: Dataset integration tests
  .kokoro/samples/python3.8/common.cfg
  google/cloud/aiplatform/schema.py
  noxfile.py
  tests/system/aiplatform/test_dataset.py
Labels: cla: yes

#157 chore: update CODEOWNERS with GAPIC and SDK dev teams
  .github/CODEOWNERS
Labels: cla: yes

#156 feat: Added batch prediction tabular forecasting sample
  .sample_configs/param_handlers/create_batch_prediction_job_tabular_forecasting_sample.py
  samples/snippets/create_batch_prediction_job_tabular_forecasting_sample.py
  samples/snippets/create_batch_prediction_job_tabular_forecasting_sample_test.py
Labels: cla: yes, samples

#155 test: add constraints file
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
Labels: cla: yes

#153 feat: specialized dataset classes, fix: datasets refactor
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/datasets/__init__.py
  google/cloud/aiplatform/datasets/_datasources.py
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/schema.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_end_to_end.py
Labels: cla: yes

#158 chore: aiplatform.schema -> aiplatform.gapic.schema
  .sample_configs/process_configs.yaml
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/gapic/__init__.py
  google/cloud/aiplatform/gapic/schema/__init__.py
  samples/snippets/create_training_pipeline_image_classification_sample.py
  samples/snippets/create_training_pipeline_image_object_detection_sample.py
  samples/snippets/create_training_pipeline_tabular_forecasting_sample.py
  samples/snippets/create_training_pipeline_text_classification_sample.py
  samples/snippets/create_training_pipeline_text_entity_extraction_sample.py
  samples/snippets/create_training_pipeline_text_sentiment_analysis_sample.py
  samples/snippets/create_training_pipeline_video_action_recognition_sample.py
  samples/snippets/create_training_pipeline_video_classification_sample.py
  samples/snippets/create_training_pipeline_video_object_tracking_sample.py
  samples/snippets/predict_image_classification_sample.py
  samples/snippets/predict_image_object_detection_sample.py
  samples/snippets/predict_text_classification_single_label_sample.py
  samples/snippets/predict_text_entity_extraction_sample.py
  samples/snippets/predict_text_sentiment_analysis_sample.py
Labels: cla: yes

#152 feat: Add AutoML Image Training Job class
  google/cloud/aiplatform/constants.py
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
Labels: cla: yes

#164 feat: Add custom container support
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#162 chore: merge main into dev
  .github/CODEOWNERS
  .sample_configs/param_handlers/create_batch_prediction_job_tabular_forecasting_sample.py
  samples/snippets/create_batch_prediction_job_tabular_forecasting_sample.py
  samples/snippets/create_batch_prediction_job_tabular_forecasting_sample_test.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  testing/constraints-3.6.txt
  testing/constraints-3.7.txt
Labels: cla: yes

#160 fix: suppress no project id warning
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/initializer.py
  google/cloud/aiplatform/utils.py
Labels: cla: yes

#168 Fixed incorrect key for AutoMLTrainingJob
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
Labels: cla: yes

#165 feat: Add delete methods, add list_models and undeploy_all for Endpoint class
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
Labels: automerge, cla: yes

#171 fix: Fixed bug causing training failure for object detection
  google/cloud/aiplatform/training_jobs.py
Labels: cla: yes

#166 fix: Support intermediary BQ Table for Custom Training
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#173 chore: add AutoMLImageTrainingJob to aiplatform namespace
  google/cloud/aiplatform/__init__.py
Labels: cla: yes

#174 fix: Unblock build
  google/cloud/aiplatform/base.py
Labels: cla: yes

#167 fix: default credentials config related test failures
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/initializer.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#181 Fix: pass bq_destination to input data config when using training script
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#184 chore: Update aiplatform test directory CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#187 fix(deps): remove optional dependencies
  setup.py
Labels: cla: yes

#180 feat: add TextDataset class
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/datasets/__init__.py
  google/cloud/aiplatform/datasets/_datasources.py
  google/cloud/aiplatform/datasets/text_dataset.py
  tests/unit/aiplatform/test_datasets.py
Labels: cla: yes

#177 feat: add CustomPythonPackageTrainingJob
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: cla: yes

#195 build: migrate to flakybot
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes
