Repository googleapis/python-aiplatform, pull requests merged in 2022-09, with the labels that each got.

#1633 chore: add aiplatform.init back to model monitoring system tests
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: xs, api: vertex-ai

#1620 feat: support raw_predict for Endpoint
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/constants/base.py
  google/cloud/aiplatform/models.py
  setup.py
  tests/system/aiplatform/test_model_interactions.py
  tests/system/aiplatform/test_model_upload.py
  tests/unit/aiplatform/test_models.py
Labels: size: l, api: vertex-ai

#1627 chore: e2e tabular system test improvement
  tests/system/aiplatform/e2e_base.py
  tests/system/aiplatform/test_e2e_tabular.py
Labels: size: m, api: vertex-ai

#1642 chore: add aiplatform.init to test_model_interactions.py
  tests/system/aiplatform/test_model_interactions.py
Labels: size: xs, api: vertex-ai

#1600 feat: update the samples of hyperparameter tuning in the public doc
  samples/model-builder/cancel_hyperparameter_tuning_job_sample.py
  samples/model-builder/cancel_hyperparameter_tuning_job_sample_test.py
  samples/model-builder/conftest.py
  samples/model-builder/create_hyperparameter_tuning_job_sample.py
  samples/model-builder/create_hyperparameter_tuning_job_sample_test.py
  samples/model-builder/delete_hyperparameter_tuning_job_sample.py
  samples/model-builder/delete_hyperparameter_tuning_job_sample_test.py
  samples/model-builder/get_hyperparameter_tuning_job_sample.py
  samples/model-builder/get_hyperparameter_tuning_job_sample_test.py
  samples/model-builder/test_constants.py
Labels: samples, size: l, api: vertex-ai

#1593 feat: add input artifact when creating a pipeline
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/pipeline_utils.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_utils.py
Labels: size: s, api: vertex-ai

#1643 chore: Convert enable probabilistic inference from additional experime…
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
Labels: size: m, api: vertex-ai

#1639 chore: Install uvicorn[standard] for cython versions of libraries to improve…
  setup.py
Labels: automerge, size: xs, api: vertex-ai

#1649 docs: ExperimentRun docstring and end_run kwarg
  google/cloud/aiplatform/metadata/experiment_run_resource.py
Labels: automerge, size: xs, api: vertex-ai

#1650 chore: Add TF 2.9 and XGB 1.6 to prediction first-party support.
  google/cloud/aiplatform/constants/prediction.py
Labels: automerge, size: xs, api: vertex-ai

#1648 feat: add eval metrics types to get_experiment_df
  google/cloud/aiplatform/metadata/constants.py
  google/cloud/aiplatform/pipeline_jobs.py
  tests/unit/aiplatform/test_metadata.py
Labels: size: s, api: vertex-ai

#1651 Revert "chore: e2e tabular system test improvement"
  tests/system/aiplatform/e2e_base.py
  tests/system/aiplatform/test_e2e_tabular.py
Labels: size: m, api: vertex-ai

#1547 tests: Added a unit test that checks the arguments that the PipelineJob.submit method passes to gcs_utils.create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: automerge, size: s, api: vertex-ai

#1644 feat: adding Python 3.10 support + updating google-vizier version
  CONTRIBUTING.rst
  google/cloud/aiplatform/vizier/pyvizier/__init__.py
  noxfile.py
  owlbot.py
  setup.py
Labels: size: s, api: vertex-ai

#1659 chore: Replace collections.Iterable reference to collections.abc.Iterable for Python 3.10
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  tests/unit/aiplatform/test_metadata.py
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: automerge, size: m, api: vertex-ai

#1614 feat: add enable_simple_view to PipelineJob.list()
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/constants/pipeline.py
  google/cloud/aiplatform/pipeline_jobs.py
  tests/system/aiplatform/test_pipeline_job.py
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: size: m, api: vertex-ai

#1665 chore: change enable_simple_view default to False
  google/cloud/aiplatform/pipeline_jobs.py
Labels: size: s, api: vertex-ai

#1687 chore: update codeowners for pipeline job client
  .github/CODEOWNERS
Labels: size: xs, api: vertex-ai

#1683 feat: add support for HTTPS URI pipeline templates
  google/cloud/aiplatform/constants/pipeline.py
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/yaml_utils.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_utils.py
Labels: automerge, size: m, api: vertex-ai

#1701 chore: Add headers for CPR model server errors.
  google/cloud/aiplatform/constants/prediction.py
  google/cloud/aiplatform/prediction/handler.py
  google/cloud/aiplatform/prediction/model_server.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: m, api: vertex-ai

#1671 fix: fix endpoint parsing in ModelDeploymentMonitoringJob.update
  google/cloud/aiplatform/jobs.py
  tests/system/aiplatform/test_model_monitoring.py
  tests/unit/aiplatform/test_jobs.py
Labels: size: m, api: vertex-ai

#1709 docs: fix typos
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/featurestore/entity_type.py
  google/cloud/aiplatform/training_jobs.py
Labels: size: s, api: vertex-ai

#1698 feat: Support complex metrics in Vertex Experiments
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  google/cloud/aiplatform/metadata/metadata.py
  google/cloud/aiplatform/metadata/schema/google/artifact_schema.py
  google/cloud/aiplatform/metadata/schema/utils.py
  samples/model-builder/conftest.py
  samples/model-builder/experiment_tracking/get_experiment_run_classification_metrics_sample.py
  samples/model-builder/experiment_tracking/get_experiment_run_classification_metrics_sample_test.py
  samples/model-builder/experiment_tracking/log_classification_metrics_sample.py
  samples/model-builder/experiment_tracking/log_classification_metrics_sample_test.py
  samples/model-builder/test_constants.py
  tests/system/aiplatform/test_experiments.py
  tests/unit/aiplatform/test_metadata.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: l, api: vertex-ai

#1700 fix: project/location parsing for nested resources
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/utils/__init__.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_utils.py
Labels: size: m, api: vertex-ai

#1707 docs: show inherited SDK methods in pydoc
  docs/aiplatform/services.rst
  google/cloud/aiplatform/training_jobs.py
Labels: automerge, size: m, api: vertex-ai
