Repository googleapis/python-aiplatform, pull requests merged in 2022-03, with the labels that each got.

#1043 fix: update system test_model_upload to use BUILD_SPECIFIC_GCP_PROJECT
  tests/system/aiplatform/test_model_upload.py
Labels: automerge

#1037 feat: Add CPR M2 sample notebook
  samples/notebooks/prediction/SDK_Custom_Predict.ipynb
Labels: samples

#1020 fix: Fix create_lit_model_from_endpoint not accepting models that don't return a dictionary.
  google/cloud/aiplatform/explain/lit.py
  tests/unit/aiplatform/test_explain_lit.py
Labels: automerge

#1044 feat: Add a notebook sample for CPR SDK integration modified from Custom
  google/cloud/aiplatform/prediction/sklearn/__init__.py
  google/cloud/aiplatform/prediction/sklearn/predictor.py
  samples/notebooks/prediction/SDK_Custom_Predict.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
Labels: samples

#1052 feat: Add M4 preprocess sample
  samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
Labels: samples

#1053 fix: Updated naming to be unique across samples.
  samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
Labels: samples

#1056 fix: missing reference to logged_web_access_uris
  google/cloud/aiplatform/jobs.py
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_hyperparameter_tuning_job.py
Labels: automerge

#865 fix: Honoring the model's supported_deployment_resources_types
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: automerge, cla: yes, api: aiplatform

#1065 feat: Add support for Vertex Tables Q1 regions
  google/cloud/aiplatform/constants/base.py
  tests/unit/aiplatform/test_utils.py
Labels: automerge

#1046 docs(samples): read, import, batch_serve, batch_create features
  samples/model-builder/batch_create_features_sample.py
  samples/model-builder/batch_create_features_sample_test.py
  samples/model-builder/batch_serve_features_to_bq_sample.py
  samples/model-builder/batch_serve_features_to_bq_sample_test.py
  samples/model-builder/conftest.py
  samples/model-builder/import_feature_values_sample.py
  samples/model-builder/import_feature_values_sample_test.py
  samples/model-builder/read_feature_values_sample.py
  samples/model-builder/read_feature_values_sample_test.py
  samples/model-builder/test_constants.py
Labels: samples

#987 docs: Update AutoML Video docstring
  google/cloud/aiplatform/training_jobs.py
Labels: automerge

#1068 fix: add resource manager utils to get project ID from project number
  google/cloud/aiplatform/featurestore/entity_type.py
  google/cloud/aiplatform/featurestore/featurestore.py
  google/cloud/aiplatform/utils/resource_manager_utils.py
  setup.py
  tests/unit/aiplatform/test_featurestores.py
Labels: automerge

#1076 fix: Fix import error string showing wrong pip install path
  google/cloud/aiplatform/explain/lit.py
Labels: automerge

#760 chore: fix typos
  README.rst
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/metadata/metadata.py
  google/cloud/aiplatform/tensorboard/uploader_utils.py
  google/cloud/aiplatform/training_jobs.py
  google/cloud/aiplatform/utils/pipeline_utils.py
  google/cloud/aiplatform/utils/source_utils.py
  google/cloud/aiplatform/utils/worker_spec_utils.py
Labels: automerge, type: cleanup, cla: yes, api: aiplatform

#1094 feat: Add timeout arguments to Endpoint.predict and Endpoint.explain
  google/cloud/aiplatform/models.py
  tests/system/aiplatform/test_e2e_tabular.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
Labels: automerge

#1096 chore: fix check project ID inference system test
  tests/system/aiplatform/test_project_id_inference.py
Labels: automerge

#1102 docs: Include time dependency in documentation for weight, time, and target columns.
  google/cloud/aiplatform/training_jobs.py
Labels: automerge

#1101 docs: fix CustomContainerTrainingJob example in docstring
  google/cloud/aiplatform/training_jobs.py
Labels: automerge

#1104 chore: update docstring for column_transformations and column_specs
  google/cloud/aiplatform/training_jobs.py
Labels: automerge

#1098 docs: improve bigquery_destination_prefix docstring
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
Labels: automerge

#1127 chore: update docstring for column_specs and column_transformations to specify local credentials
  google/cloud/aiplatform/training_jobs.py
Labels: automerge
