Repository googleapis/python-aiplatform, pull requests merged in 2022-10, with the labels that each got.

#1708 chore: surface CPR docs, and reformat docstrings
  docs/aiplatform/prediction.rst
  docs/index.rst
  google/cloud/aiplatform/prediction/local_endpoint.py
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/predictor.py
Labels: automerge, size: m, api: vertex-ai

#1713 chore: adding SDK team to CODEOWNERS
  .github/CODEOWNERS
Labels: size: xs, api: vertex-ai

#1716 docs: fix create experiment sample
  samples/model-builder/experiment_tracking/create_experiment_sample.py
  samples/model-builder/experiment_tracking/create_experiment_sample_test.py
Labels: samples, size: xs, api: vertex-ai

#1719 chore: expose model registry class
  google/cloud/aiplatform/__init__.py
Labels: size: xs, api: vertex-ai

#1717 fix: PipelineJob should only pass bearer tokens for AR URIs
  google/cloud/aiplatform/utils/yaml_utils.py
  tests/unit/aiplatform/test_utils.py
Labels: automerge, size: s, api: vertex-ai

#1720 fix(deps): allow protobuf 3.19.5
  setup.py
  testing/constraints-3.7.txt
Labels: size: xs, api: vertex-ai

#1725 chore: merge v1.18.1 into main
  CHANGELOG.md
  google/cloud/aiplatform/version.py
Labels: size: s, api: vertex-ai

#1739 chore: fix typo in readme
  README.rst
Labels: size: xs, api: vertex-ai

#1718 fix: added proto message conversion to MDMJob.update fields
  google/cloud/aiplatform/jobs.py
  tests/unit/aiplatform/test_jobs.py
Labels: size: m, api: vertex-ai

#1737 fix: enable profile uploading feature
  google/cloud/aiplatform/tensorboard/uploader.py
  tests/unit/aiplatform/test_uploader.py
Labels: size: m, api: vertex-ai, ready to pull
