Repository googleapis/python-aiplatform, pull requests merged in 2022-07, with the labels that each got.

#1456 feature: Update OOB predictors to accept more model filenames.
  google/cloud/aiplatform/constants/prediction.py
  google/cloud/aiplatform/prediction/sklearn/predictor.py
  google/cloud/aiplatform/prediction/xgboost/predictor.py
Labels: size: m, api: vertex-ai

#1471 chore: move pipeline constants to constants file
  google/cloud/aiplatform/constants/pipeline.py
  google/cloud/aiplatform/pipeline_jobs.py
Labels: size: m, api: vertex-ai

#1476 feat: add get_associated_experiment method to pipeline_jobs
  google/cloud/aiplatform/pipeline_jobs.py
  tests/system/aiplatform/test_experiments.py
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: size: m, api: vertex-ai

#1470 test: Fixed CPR system test.
  tests/system/aiplatform/test_prediction_cpr.py
  tests/system/aiplatform/test_resources/__init__.py
  tests/system/aiplatform/test_resources/cpr_model/model.joblib
  tests/system/aiplatform/test_resources/cpr_user_code/__init__.py
  tests/system/aiplatform/test_resources/cpr_user_code/predictor.py
Labels: size: s, api: vertex-ai

#1480 chore: update lit explain mocks
  tests/unit/aiplatform/test_explain_lit.py
Labels: size: s, api: vertex-ai

#1482 chore: add skipif to tests that rely on sys.executable
  tests/unit/aiplatform/test_training_utils.py
Labels: size: xs, api: vertex-ai

#1477 chore: Fixed CPR GCS bug, allowed local util logging to set encoding, and removed limitation on predictor init method.
  google/cloud/aiplatform/docker_utils/build.py
  google/cloud/aiplatform/docker_utils/local_util.py
  google/cloud/aiplatform/prediction/predictor.py
  google/cloud/aiplatform/utils/prediction_utils.py
  tests/unit/aiplatform/test_docker_utils.py
Labels: size: m, api: vertex-ai

#1485 ci: Change install nox command to use the default python.
  .kokoro/test-samples-impl.sh
Labels: size: xs, api: vertex-ai

#1465 feat: Add support for start_execution in MLMD SDK.
  google/cloud/aiplatform/metadata/schema/base_execution.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: m, api: vertex-ai

#1462 feat: Add sample for create artifact and execution using the Metadata SDK.
  samples/model-builder/conftest.py
  samples/model-builder/experiment_tracking/create_artifact_with_sdk_sample.py
  samples/model-builder/experiment_tracking/create_artifact_with_sdk_sample_test.py
  samples/model-builder/experiment_tracking/create_execution_with_sdk_sample.py
  samples/model-builder/experiment_tracking/create_execution_with_sdk_sample_test.py
Labels: samples, size: m, api: vertex-ai

#1489 chore: pin python3.6 revert for OwlBot
  owlbot.py
Labels: size: xs, api: vertex-ai

#1486 chore: Update metadata tests to use google_auth_mock.
  samples/model-builder/noxfile.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: s, api: vertex-ai

#1449 chore: Merged LocalModel.create into init and removed upload method from LocalModel class.
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/prediction/README.md
  google/cloud/aiplatform/prediction/local_model.py
  samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
  samples/notebooks/prediction/SDK_Pytorch_Custom_Predict.ipynb
  samples/notebooks/prediction/SDK_Triton_PyTorch_Local_Prediction.ipynb
  tests/system/aiplatform/test_prediction_cpr.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: l, api: vertex-ai

#1493 chore: Fixed the first half of the comments in the main PR for CPR.
  google/cloud/aiplatform/prediction/README.md
  google/cloud/aiplatform/prediction/handler.py
  google/cloud/aiplatform/prediction/serializer.py
  google/cloud/aiplatform/prediction/sklearn/predictor.py
  google/cloud/aiplatform/prediction/xgboost/predictor.py
  google/cloud/aiplatform/utils/prediction_utils.py
  pytest.ini
  tests/system/aiplatform/test_prediction_cpr.py
Labels: size: m, api: vertex-ai

#1498 feat: Add support for Vertex Tables Q2 regions
  google/cloud/aiplatform/constants/base.py
Labels: size: xs, api: vertex-ai

#1506 chore: Fixed GCS bug and unit tests.
  google/cloud/aiplatform/utils/prediction_utils.py
  tests/system/aiplatform/test_prediction_cpr.py
  tests/unit/aiplatform/test_utils.py
Labels: size: s, api: vertex-ai

#1415 feat: Added the PipelineJob.from_pipeline_func method
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/gcs_utils.py
  google/cloud/aiplatform/utils/resource_manager_utils.py
  tests/system/aiplatform/test_pipeline_job.py
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: automerge, size: l, api: vertex-ai

#1511 chore: Created CPR model server and modified the way to build images.
  google/cloud/aiplatform/docker_utils/build.py
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/model_server.py
  google/cloud/aiplatform/utils/prediction_utils.py
  tests/unit/aiplatform/test_docker_utils.py
  tests/unit/aiplatform/test_prediction.py
  tests/unit/aiplatform/test_utils.py
Labels: size: xl, api: vertex-ai

#1518 chore: use smaller data file in dataset import test
  tests/system/aiplatform/test_dataset.py
Labels: size: xs, api: vertex-ai

#1520 chore: update index id in matching engine system test
  tests/system/aiplatform/test_matching_engine_index.py
Labels: size: xs, api: vertex-ai

#1515 chore: Add code owners for Vertex Metadata SDK
  .github/CODEOWNERS
Labels: size: xs, api: vertex-ai

#1528 samples: Removed CPR samples for merging into the main branch.
  samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
  samples/notebooks/prediction/SDK_Pytorch_Custom_Predict.ipynb
  samples/notebooks/prediction/SDK_Triton_PyTorch_Local_Prediction.ipynb
Labels: samples, size: xl, api: vertex-ai

#1521 chore: Update docstring for Predictor to be clearer
  google/cloud/aiplatform/prediction/predictor.py
Labels: size: s, api: vertex-ai

#1519 feat: Change the Metadata SDK _Context class to an external class
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/metadata/context.py
  google/cloud/aiplatform/metadata/experiment_resources.py
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  google/cloud/aiplatform/metadata/metadata.py
  google/cloud/aiplatform/metadata/schema/base_context.py
  google/cloud/aiplatform/metadata/schema/system/context_schema.py
  google/cloud/aiplatform/pipeline_jobs.py
  tests/unit/aiplatform/test_metadata_resources.py
  tests/unit/aiplatform/test_metadata_schema.py
  tests/unit/aiplatform/test_utils.py
Labels: size: l, api: vertex-ai

#1527 chore: change dataset url in dataset import system test
  tests/system/aiplatform/test_dataset.py
Labels: size: xs, api: vertex-ai

#1514 feat: Add metadata SDK samples for list artifact and list execution
  samples/model-builder/conftest.py
  samples/model-builder/experiment_tracking/list_artifact_sample.py
  samples/model-builder/experiment_tracking/list_artifact_sample_test.py
  samples/model-builder/experiment_tracking/list_execution_sample.py
  samples/model-builder/experiment_tracking/list_execution_sample_test.py
  samples/model-builder/test_constants.py
Labels: samples, size: m, api: vertex-ai

#1530 feat: Add metadata SDK sample for delete method.
  samples/model-builder/conftest.py
  samples/model-builder/experiment_tracking/delete_artifact_sample.py
  samples/model-builder/experiment_tracking/delete_artifact_sample_test.py
  samples/model-builder/experiment_tracking/delete_context_sample.py
  samples/model-builder/experiment_tracking/delete_context_sample_test.py
  samples/model-builder/experiment_tracking/delete_execution_sample.py
  samples/model-builder/experiment_tracking/delete_execution_sample_test.py
Labels: samples, size: m, api: vertex-ai

#1483 feat: Support custom containers in CustomJob.from_local_script
  google/cloud/aiplatform/jobs.py
  tests/system/aiplatform/test_custom_job.py
  tests/system/aiplatform/test_resources/custom_job_script.py
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: l, api: vertex-ai

#1537 fix: Pass the PipelineJob credentials to `create_gcs_bucket_for_pipeline_artifacts_if_it_does_not_exist`
  google/cloud/aiplatform/pipeline_jobs.py
Labels: size: xs, api: vertex-ai

#1536 Feat: Refactor schema classes to subclass from _Resource
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/metadata/artifact.py
  google/cloud/aiplatform/metadata/execution.py
  google/cloud/aiplatform/metadata/resource.py
  google/cloud/aiplatform/metadata/schema/base_artifact.py
  google/cloud/aiplatform/metadata/schema/base_context.py
  google/cloud/aiplatform/metadata/schema/base_execution.py
  google/cloud/aiplatform/metadata/schema/utils.py
  samples/model-builder/conftest.py
  samples/model-builder/experiment_tracking/create_artifact_with_sdk_sample_test.py
  samples/model-builder/experiment_tracking/create_execution_with_sdk_sample_test.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: l, api: vertex-ai

#1540 chore: Append users' src dir name to sys.path while model server starts for CPR.
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/model_server.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: s, api: vertex-ai

#1542 fix: Fixed getting the output GCS bucket in PipelineJob.submit
  google/cloud/aiplatform/pipeline_jobs.py
Labels: automerge, size: s, api: vertex-ai

#1249 feat: SDK support for model monitoring
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/compat/__init__.py
  google/cloud/aiplatform/compat/types/__init__.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/model_monitoring/__init__.py
  google/cloud/aiplatform/model_monitoring/alert.py
  google/cloud/aiplatform/model_monitoring/objective.py
  google/cloud/aiplatform/model_monitoring/sampling.py
  google/cloud/aiplatform/model_monitoring/schedule.py
  tests/system/aiplatform/test_model_monitoring.py
  tests/unit/aiplatform/test_model_monitoring.py
Labels: size: xl, api: vertex-ai

#1548 chore: increase system test timeout to 6 hours
  .kokoro/continuous/system.cfg
Labels: size: xs, api: vertex-ai

#1434 feat: Vertex Vizier support in SDK.
  .coveragerc
  google/cloud/aiplatform/compat/__init__.py
  google/cloud/aiplatform/compat/services/__init__.py
  google/cloud/aiplatform/compat/types/__init__.py
  google/cloud/aiplatform/utils/__init__.py
  google/cloud/aiplatform/vizier/__init__.py
  google/cloud/aiplatform/vizier/client_abc.py
  google/cloud/aiplatform/vizier/pyvizier/__init__.py
  google/cloud/aiplatform/vizier/pyvizier/automated_stopping.py
  google/cloud/aiplatform/vizier/pyvizier/proto_converters.py
  google/cloud/aiplatform/vizier/pyvizier/study_config.py
  google/cloud/aiplatform/vizier/study.py
  google/cloud/aiplatform/vizier/trial.py
  samples/model-builder/requirements.txt
  setup.py
  tests/system/aiplatform/test_vizier.py
  tests/unit/aiplatform/test_vizier.py
Labels: size: xl, api: vertex-ai

#1556 chore: increase kokoro VM timeout for system tests
  .kokoro/continuous/system.cfg
Labels: size: xs, api: vertex-ai
