Repository googleapis/python-aiplatform, pull requests merged in 2022-08, with the labels that each got.

#1553 fix: Correct docstring in Dataset classes
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/time_series_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
Labels: size: s, api: vertex-ai

#1549 Feat: Add google.ClassificationMetrics, google.RegressionMetrics, and google.Forecasting Metrics
  google/cloud/aiplatform/metadata/schema/google/artifact_schema.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: l, api: vertex-ai

#1544 feat: added support for conditional parameters in hyperparameter tuning
  google/cloud/aiplatform/hyperparameter_tuning.py
  tests/unit/aiplatform/test_hyperparameter_tuning_job.py
Labels: size: m, api: vertex-ai

#1565 chore: fix resource deletion issues with model monitoring system tests
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: s, api: vertex-ai

#1513 chore: remove TODOs from docs
  google/cloud/aiplatform/training_jobs.py
Labels: size: xs, api: vertex-ai

#923 docs(samples): add AutoML image classification sample
  samples/model-builder/predict_image_classification_sample.py
  samples/model-builder/predict_image_classification_sample_test.py
Labels: samples, size: m, api: vertex-ai

#1578 chore: add manual resource removal to model monitoring system tests
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: s, api: vertex-ai

#1585 Feat: Add samples for get execution input and output artifacts
  samples/model-builder/experiment_tracking/get_execution_input_artifacts_sample.py
  samples/model-builder/experiment_tracking/get_execution_input_artifacts_sample_test.py
  samples/model-builder/experiment_tracking/get_execution_output_artifacts_sample.py
  samples/model-builder/experiment_tracking/get_execution_output_artifacts_sample_test.py
Labels: samples, size: m, api: vertex-ai

#1586 chore: update expeirments sample to use correct param names
  samples/model-builder/experiment_tracking/log_pipeline_job_sample.py
Labels: samples, size: xs, api: vertex-ai

#1588 fix: log_metrics docstring error
  google/cloud/aiplatform/metadata/experiment_run_resource.py
Labels: size: xs, api: vertex-ai

#1587 fix(deps): allow protobuf < 5.0.0
  setup.py
  testing/constraints-3.7.txt
Labels: automerge, size: xs, api: vertex-ai

#1570 feat: support model monitoring for batch prediction in Vertex SDK
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/model_monitoring/alert.py
  google/cloud/aiplatform/model_monitoring/objective.py
  tests/system/aiplatform/test_model_monitoring.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_model_monitoring.py
Labels: size: l, api: vertex-ai

#1599 chore: fix incorrect syntax in model monitoring system tests
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: xs, api: vertex-ai

#1591 feat: Add support for SDK Method metrics tracking via _USER_AGENT_SDK…
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/constants/base.py
  google/cloud/aiplatform/metadata/artifact.py
  google/cloud/aiplatform/metadata/context.py
  google/cloud/aiplatform/metadata/execution.py
  google/cloud/aiplatform/metadata/metadata_store.py
  google/cloud/aiplatform/metadata/schema/base_artifact.py
  google/cloud/aiplatform/metadata/schema/base_context.py
  google/cloud/aiplatform/metadata/schema/base_execution.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: l, api: vertex-ai

#1594 fix: Study.list() method
  google/cloud/aiplatform/base.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_tensorboard.py
Labels: size: s, api: vertex-ai

#1603 chore: shorten image dataset display name in system test
  tests/system/aiplatform/test_dataset.py
Labels: size: xs, api: vertex-ai

#1572 chore: Remove outer directories for building CPR images.
  google/cloud/aiplatform/docker_utils/build.py
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/model_server.py
  google/cloud/aiplatform/utils/prediction_utils.py
  tests/unit/aiplatform/test_docker_utils.py
  tests/unit/aiplatform/test_prediction.py
  tests/unit/aiplatform/test_utils.py
Labels: size: l, api: vertex-ai

#1602 docs(samples): add Model Registry samples to Vertex AI Python SDK
  samples/model-builder/conftest.py
  samples/model-builder/model_registry/assign_aliases_model_version_sample.py
  samples/model-builder/model_registry/assign_aliases_model_version_sample_test.py
  samples/model-builder/model_registry/create_aliased_model_sample.py
  samples/model-builder/model_registry/create_aliased_model_sample_test.py
  samples/model-builder/model_registry/create_default_model_sample.py
  samples/model-builder/model_registry/create_default_model_sample_test.py
  samples/model-builder/model_registry/create_model_registry_sample.py
  samples/model-builder/model_registry/create_model_registry_sample_test.py
  samples/model-builder/model_registry/delete_aliases_model_version_sample.py
  samples/model-builder/model_registry/delete_aliases_model_version_sample_test.py
  samples/model-builder/model_registry/delete_model_sample.py
  samples/model-builder/model_registry/delete_model_sample_test.py
  samples/model-builder/model_registry/delete_model_version_sample.py
  samples/model-builder/model_registry/delete_model_version_sample_test.py
  samples/model-builder/model_registry/get_model_version_info_sample.py
  samples/model-builder/model_registry/get_model_version_info_sample_test.py
  samples/model-builder/model_registry/get_registered_model_version_sample.py
  samples/model-builder/model_registry/get_registered_model_version_sample_test.py
  samples/model-builder/model_registry/list_model_versions_with_model_registry_sample.py
  samples/model-builder/model_registry/list_model_versions_with_model_registry_sample_test.py
  samples/model-builder/model_registry/upload_new_aliased_model_version_sample.py
  samples/model-builder/model_registry/upload_new_aliased_model_version_sample_test.py
  samples/model-builder/model_registry/upload_new_default_model_version_sample.py
  samples/model-builder/model_registry/upload_new_default_model_version_sample_test.py
  samples/model-builder/model_registry/upload_new_model_version_using_custom_training_pipeline_sample.py
  samples/model-builder/model_registry/upload_new_model_version_using_custom_training_pipeline_test.py
  samples/model-builder/test_constants.py
Labels: samples, size: xl, api: vertex-ai

#1610 chore: fix param names in experiments samples
  samples/model-builder/experiment_tracking/log_metrics_sample.py
  samples/model-builder/experiment_tracking/log_params_sample.py
Labels: samples, size: xs, api: vertex-ai

#1609 feat: Support ResourceName with Version.
  google/cloud/aiplatform/metadata/resource.py
  google/cloud/aiplatform/metadata/schema/utils.py
  tests/unit/aiplatform/test_metadata_resources.py
  tests/unit/aiplatform/test_metadata_schema.py
Labels: size: m, api: vertex-ai

#1597 chore: Refine the error messages for extra prediction packages and
  google/cloud/aiplatform/docker_utils/run.py
  google/cloud/aiplatform/docker_utils/utils.py
  google/cloud/aiplatform/prediction/README.md
  google/cloud/aiplatform/prediction/handler.py
  google/cloud/aiplatform/prediction/handler_utils.py
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/model_server.py
  google/cloud/aiplatform/prediction/serializer.py
Labels: size: s, api: vertex-ai

#1608 feat: Support filters in matching engine vector matching
  google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py
  tests/system/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
Labels: size: m, api: vertex-ai

#1624 chore: refactor model monitoring system test to make it more efficient
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: m, api: vertex-ai
