Repository googleapis/python-aiplatform, pull requests merged in 2022-04, with the labels that each got.

#1099 feat: add timeout arg across SDK
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
  google/cloud/aiplatform/featurestore/entity_type.py
  google/cloud/aiplatform/featurestore/feature.py
  google/cloud/aiplatform/featurestore/featurestore.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/tensorboard/tensorboard_resource.py
  google/cloud/aiplatform/training_jobs.py
  tests/system/aiplatform/test_dataset.py
  tests/system/aiplatform/test_e2e_tabular.py
  tests/system/aiplatform/test_tensorboard.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_hyperparameter_tuning_job.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_tensorboard.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: xl

#1133 fix: Set serving_container_command to entrypoint instead of command to match our requirements
  google/cloud/aiplatform/docker_utils/run.py
  tests/unit/aiplatform/test_docker_utils.py
Labels: size: s

#882 feat: Made display_name parameter optional for most calls
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/datasets/dataset.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/time_series_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/tensorboard/tensorboard_resource.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_datasets.py
Labels: automerge, cla: yes, api: aiplatform, size: m

#1108 chore: Add TF 2.8 and XGB 1.0 to prediction first-party support.
  google/cloud/aiplatform/constants/prediction.py
Labels: automerge, size: xs

#1136 ci: add system test extras
  noxfile.py
  owlbot.py
Labels: automerge, size: s

#1137 chore: remove matching engine add copyright header
  .sample_configs/param_handlers/create_batch_prediction_job_tabular_forecasting_sample.py
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/_matching_engine/__init__.py
  google/cloud/aiplatform/_matching_engine/match_service_pb2.py
  google/cloud/aiplatform/_matching_engine/match_service_pb2_grpc.py
  google/cloud/aiplatform/_matching_engine/matching_engine_index.py
  google/cloud/aiplatform/_matching_engine/matching_engine_index_config.py
  google/cloud/aiplatform/_matching_engine/matching_engine_index_endpoint.py
  samples/snippets/helpers.py
  scripts/run_flaky_test_diagnostic.py
  tests/system/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
Labels: automerge, size: m

#1089 feat(sdk): enable loading both JSON and YAML pipelines IR
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/yaml_utils.py
  setup.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_utils.py
Labels: size: l

#1149 fix: system tests failure from test_upload_and_deploy_xgboost_model
  google/cloud/aiplatform/models.py
Labels: automerge, size: xs

#1134 chore: allow releases on previous major versions
  .github/release-please.yml
  owlbot.py
Labels: size: s

#1153 docs: endpoint.create => aiplatform.Endpoint.create
  README.rst
Labels: size: s

#1154 docs: update model code snippet order in README
  README.rst
Labels: size: s

#1152 chore: Pull the image if it doesn't exist before image copying.
  google/cloud/aiplatform/docker_utils/utils.py
  google/cloud/aiplatform/prediction/local_model.py
  tests/unit/aiplatform/test_docker_utils.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: m

#1142 fix: Replace env var references in given env, command and arg.
  google/cloud/aiplatform/docker_utils/run.py
  tests/unit/aiplatform/test_docker_utils.py
Labels: size: m

#1167 feat: add ModelEvaluation support
  README.rst
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/model_evaluation/__init__.py
  google/cloud/aiplatform/model_evaluation/model_evaluation.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_model_evaluation.py
  tests/unit/aiplatform/test_models.py
Labels: size: l

#1168 feat: Add endpoind_id arg to Endpoint#create
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_endpoints.py
Labels: automerge, size: m

#1175 fix: change default for create_request_timeout arg to None
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: automerge, size: m

#1180 feat: allow creating featurestore without online node
  google/cloud/aiplatform/featurestore/featurestore.py
  tests/system/aiplatform/test_featurestore.py
Labels: size: xs

#1183 chore: add tests for timeout arg not being explicitly set
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_tensorboard.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: l
