Repository googleapis/python-aiplatform, pull requests merged in 2022-06, with the labels that each got.

#1404 docs: fix changelog header to consistent size
  CHANGELOG.md
Labels: size: xs, api: vertex-ai

#1233 chore: update python-samples-owners to reviewers group
  .github/CODEOWNERS
Labels: samples, size: xs, api: vertex-ai

#1403 chore: updates so tests can run in different environments
  tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf1_test.py
  tests/unit/aiplatform/test_explain_saved_model_metadata_builder_tf2_test.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: xs, api: vertex-ai

#1239 feat: add a way to easily clone a PipelineJob
  google/cloud/aiplatform/pipeline_jobs.py
  tests/unit/aiplatform/test_pipeline_jobs.py
Labels: size: l, api: vertex-ai

#1196 feat: add seq2seq forecasting training job
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/schema.py
  google/cloud/aiplatform/training_jobs.py
  tests/system/aiplatform/test_e2e_forecasting.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
Labels: automerge, size: xl, api: vertex-ai

#1406 feature: Add OOB XgboostPredictor
  google/cloud/aiplatform/prediction/xgboost/__init__.py
  google/cloud/aiplatform/prediction/xgboost/predictor.py
Labels: size: m, api: vertex-ai

#1409 fix: change endpoint update method to return resource
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_endpoints.py
Labels: size: s, api: vertex-ai

#1398 fix: Pinned protobuf to prevent issues with pb files.
  setup.py
  testing/constraints-3.6.txt
Labels: size: xs, api: vertex-ai

#1412 chore: update import statement in test_uploader
  tests/unit/aiplatform/test_uploader.py
Labels: size: xs, api: vertex-ai

#1416 feat: support dataset update
  google/cloud/aiplatform/datasets/dataset.py
  tests/system/aiplatform/test_dataset.py
  tests/unit/aiplatform/test_datasets.py
Labels: size: m, api: vertex-ai

#1408 fix: Fixed comments from the merging PR.
  google/cloud/aiplatform/docker_utils/build.py
  google/cloud/aiplatform/docker_utils/run.py
  google/cloud/aiplatform/docker_utils/utils.py
  google/cloud/aiplatform/prediction/README.md
  google/cloud/aiplatform/prediction/handler.py
  google/cloud/aiplatform/prediction/handler_utils.py
  google/cloud/aiplatform/prediction/local_model.py
  google/cloud/aiplatform/prediction/model_server.py
  google/cloud/aiplatform/prediction/predictor.py
  google/cloud/aiplatform/prediction/serializer.py
  google/cloud/aiplatform/prediction/sklearn/predictor.py
  google/cloud/aiplatform/prediction/xgboost/predictor.py
  setup.py
Labels: size: m, api: vertex-ai

#1433 chore: performance improvements to unit tests
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: l, api: vertex-ai

#1436 ci: Don't include unit tests in calculation of test coverage
  noxfile.py
  owlbot.py
  samples/model-builder/noxfile.py
Labels: size: s, api: vertex-ai

#1232 chore: Removed Python 3.6 support
  .kokoro/continuous/unit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic-head.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  CONTRIBUTING.rst
  README.rst
  mypy.ini
  noxfile.py
  owlbot.py
  samples/model-builder/noxfile.py
  samples/snippets/noxfile.py
  scripts/readme-gen/templates/install_deps.tmpl.rst
  setup.py
Labels: automerge, size: m, api: vertex-ai

#1432 chore: fix sample and integration tests
  .github/CODEOWNERS
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.8/periodic.cfg
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  google/cloud/aiplatform/metadata/resource.py
  owlbot.py
  samples/model-builder/experiment_tracking/assign_artifact_as_execution_input_sample.py
  samples/model-builder/requirements.txt
  setup.py
  tests/system/aiplatform/test_experiments.py
  tests/system/aiplatform/test_metadata.py
Labels: automerge, size: m, api: vertex-ai

#1440 chore: restore CODEOWNERS file
  .github/CODEOWNERS
Labels: owlbot:ignore, size: s, api: vertex-ai

#1405 feat: add support for accepting an Artifact Registry URL in pipeline_job
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/yaml_utils.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_utils.py
Labels: size: m, api: vertex-ai

#1170 fix: Removed dirs_exist_ok parameter as it's not backwards compatible
  google/cloud/aiplatform/utils/source_utils.py
  tests/unit/aiplatform/test_training_utils.py
Labels: size: m, api: vertex-ai

#1220 fix: Fixed docstrings for wildcards and matching engine type
  google/cloud/aiplatform/datasets/_datasources.py
  google/cloud/aiplatform/datasets/image_dataset.py
  google/cloud/aiplatform/datasets/tabular_dataset.py
  google/cloud/aiplatform/datasets/text_dataset.py
  google/cloud/aiplatform/datasets/time_series_dataset.py
  google/cloud/aiplatform/datasets/video_dataset.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/matching_engine/matching_engine_index.py
  google/cloud/aiplatform/models.py
Labels: size: m, api: vertex-ai

#1452 feat: add support for failure_policy in PipelineJob
  google/cloud/aiplatform/compat/__init__.py
  google/cloud/aiplatform/compat/types/__init__.py
  google/cloud/aiplatform/pipeline_jobs.py
  google/cloud/aiplatform/utils/pipeline_utils.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_utils.py
Labels: size: m, api: vertex-ai

#1458 chore: reference pypi package in exception instead of github repo name
  google/cloud/aiplatform/metadata/experiment_resources.py
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  google/cloud/aiplatform/metadata/metadata.py
  tests/unit/aiplatform/test_metadata.py
Labels: automerge, size: s, api: vertex-ai

#1459 chore: update default state for artifacts to LIVE
  google/cloud/aiplatform/metadata/artifact.py
  tests/unit/aiplatform/test_metadata_resources.py
Labels: automerge, size: s, api: vertex-ai

#1407 chore: test minimum dependencies in python 3.7
  testing/constraints-3.7.txt
Labels: size: s, api: vertex-ai

#1236 chore: docs clarification
  README.rst
Labels: size: s, api: vertex-ai

#1461 chore: Fixed CPR sample links.
  google/cloud/aiplatform/prediction/README.md
Labels: samples, size: s, api: vertex-ai

#1428 chore: system test for model monitoring
  tests/system/aiplatform/test_model_monitoring.py
Labels: size: l, api: vertex-ai

#1464 chore: Revert "chore: Support bigquery 3.x"
  setup.py
Labels: size: xs, api: vertex-ai

#1033 feat: Add PrivateEndpoint class and HTTP methods
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/initializer.py
  google/cloud/aiplatform/models.py
  setup.py
  tests/system/aiplatform/e2e_base.py
  tests/system/aiplatform/test_private_endpoint.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_models.py
Labels: size: xl, api: vertex-ai

#1438 feat: Support for Model Versioning
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/training_jobs.py
  tests/system/aiplatform/test_model_version_management.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_metadata.py
  tests/unit/aiplatform/test_metadata_resources.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: size: xl, api: vertex-ai

#1467 chore: fix metadata schema integration tests
  tests/system/aiplatform/test_e2e_metadata_schema.py
Labels: automerge, size: s, api: vertex-ai

#1468 chore: update Vertex Model artifact resolution to use versioned model…
  google/cloud/aiplatform/metadata/artifact.py
  google/cloud/aiplatform/metadata/constants.py
  google/cloud/aiplatform/metadata/experiment_run_resource.py
  google/cloud/aiplatform/utils/rest_utils.py
  tests/unit/aiplatform/test_metadata.py
  tests/unit/aiplatform/test_metadata_resources.py
Labels: size: m, api: vertex-ai

#1439 samples: Updated Prediction CPR notebooks.
  google/cloud/aiplatform/prediction/README.md
  samples/notebooks/prediction/SDK_Custom_Predict.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Predict_and_Handler_SDK_Integration.ipynb
  samples/notebooks/prediction/SDK_Custom_Preprocess.ipynb
  samples/notebooks/prediction/SDK_Pytorch_Custom_Predict.ipynb
  samples/notebooks/prediction/SDK_Triton_PyTorch_Local_Prediction.ipynb
Labels: samples, size: xl, api: vertex-ai
