Repository googleapis/python-aiplatform, pull requests merged in 2022-05, with the labels that each got.

#1150 chore: Allow Local Endpoint to run on GPU.
  google/cloud/aiplatform/constants/prediction.py
  google/cloud/aiplatform/docker_utils/run.py
  google/cloud/aiplatform/prediction/local_endpoint.py
  google/cloud/aiplatform/prediction/local_model.py
  tests/unit/aiplatform/test_docker_utils.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: l

#1187 feat: Allow users to specify timestamp split for vertex forecasting
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
Labels: automerge, size: m

#1195 tests: Added VPC network constant
  .kokoro/continuous/continuous.cfg
  owlbot.py
Labels: size: xs

#1204 tests: Added VPC network constants to common file instead of continuous
  .kokoro/continuous/common.cfg
  .kokoro/continuous/continuous.cfg
  owlbot.py
Labels: size: s, api: vertex-ai

#1192 feat: Make matching engine API public
  google/cloud/aiplatform/__init__.py
  google/cloud/aiplatform/matching_engine/__init__.py
  google/cloud/aiplatform/matching_engine/_protos/match_service_pb2.py
  google/cloud/aiplatform/matching_engine/_protos/match_service_pb2_grpc.py
  google/cloud/aiplatform/matching_engine/matching_engine_index.py
  google/cloud/aiplatform/matching_engine/matching_engine_index_config.py
  google/cloud/aiplatform/matching_engine/matching_engine_index_endpoint.py
  tests/system/aiplatform/e2e_base.py
  tests/system/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
Labels: size: m, api: vertex-ai

#1209 chore: fix Dataset system tests
  tests/system/aiplatform/e2e_base.py
  tests/system/aiplatform/test_dataset.py
Labels: size: l, api: vertex-ai

#1194 Feat: add batch_size kwarg for batch prediction jobs
  google/cloud/aiplatform/jobs.py
  google/cloud/aiplatform/models.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_models.py
Labels: aiplatform, size: m, api: vertex-ai

#1214 chore: cleanup Dataset system tests
  tests/system/aiplatform/test_dataset.py
Labels: size: s, api: vertex-ai

#1163 docs: update aiplatform SDK arrangement for Sphinx
  docs/aiplatform/definition_v1/types.rst
  docs/aiplatform/definition_v1beta1/types.rst
  docs/aiplatform/instance_v1/types.rst
  docs/aiplatform/instance_v1beta1/types.rst
  docs/aiplatform/params_v1/types.rst
  docs/aiplatform/params_v1beta1/types.rst
  docs/aiplatform/prediction_v1/types.rst
  docs/aiplatform/prediction_v1beta1/types.rst
  docs/aiplatform/services.rst
  docs/aiplatform/types.rst
  docs/index.rst
Labels: size: s, api: vertex-ai

#1174 chore: Check in service proto file
  google/cloud/aiplatform/matching_engine/_protos/match_service.proto
Labels: size: m, api: vertex-ai

#1226 fix: Fixed the selection of accept headers for CPR handler.
  google/cloud/aiplatform/constants/prediction.py
  google/cloud/aiplatform/prediction/handler_utils.py
  google/cloud/aiplatform/prediction/serializer.py
  setup.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: m, api: vertex-ai

#1235 chore: Remove _v1 specific references in favor of compat types and services
  google/cloud/aiplatform/compat/__init__.py
  google/cloud/aiplatform/compat/types/__init__.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/pipeline_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_explain_lit.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_hyperparameter_tuning_job.py
  tests/unit/aiplatform/test_initializer.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
  tests/unit/aiplatform/test_metadata_store.py
  tests/unit/aiplatform/test_model_evaluation.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_tensorboard.py
  tests/unit/aiplatform/test_training_jobs.py
  tests/unit/aiplatform/test_uploader.py
  tests/unit/aiplatform/test_uploader_main.py
Labels: size: l, api: vertex-ai

#1191 chore: Populate user-agent while using CPR local model to upload models.
  google/cloud/aiplatform/base.py
  google/cloud/aiplatform/constants/prediction.py
  google/cloud/aiplatform/initializer.py
  google/cloud/aiplatform/models.py
  google/cloud/aiplatform/prediction/local_model.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_initializer.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_prediction.py
Labels: size: m, api: vertex-ai

#1247 chore: update system tests to tear down resources
  tests/system/aiplatform/test_dataset.py
  tests/system/aiplatform/test_featurestore.py
Labels: size: xs, api: vertex-ai

#1245 chore: add unit test mock for AnonymousCredentials
  tests/unit/aiplatform/conftest.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
  tests/unit/aiplatform/test_automl_image_training_jobs.py
  tests/unit/aiplatform/test_automl_tabular_training_jobs.py
  tests/unit/aiplatform/test_automl_text_training_jobs.py
  tests/unit/aiplatform/test_automl_video_training_jobs.py
  tests/unit/aiplatform/test_custom_job.py
  tests/unit/aiplatform/test_datasets.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_endpoints.py
  tests/unit/aiplatform/test_featurestores.py
  tests/unit/aiplatform/test_hyperparameter_tuning_job.py
  tests/unit/aiplatform/test_initializer.py
  tests/unit/aiplatform/test_jobs.py
  tests/unit/aiplatform/test_matching_engine_index.py
  tests/unit/aiplatform/test_matching_engine_index_endpoint.py
  tests/unit/aiplatform/test_metadata.py
  tests/unit/aiplatform/test_metadata_resources.py
  tests/unit/aiplatform/test_metadata_store.py
  tests/unit/aiplatform/test_model_evaluation.py
  tests/unit/aiplatform/test_models.py
  tests/unit/aiplatform/test_pipeline_jobs.py
  tests/unit/aiplatform/test_tensorboard.py
  tests/unit/aiplatform/test_training_jobs.py
  tests/unit/aiplatform/test_uploader_main.py
  tests/unit/aiplatform/test_utils.py
Labels: size: m, api: vertex-ai

#1252 chore: add tear_down_resources fixture to individual system test classes
  tests/system/aiplatform/test_e2e_tabular.py
  tests/system/aiplatform/test_metadata.py
  tests/system/aiplatform/test_model_upload.py
  tests/system/aiplatform/test_tensorboard.py
Labels: size: s, api: vertex-ai

#1162 feat: add update endpoint
  google/cloud/aiplatform/models.py
  tests/system/aiplatform/test_model_upload.py
  tests/unit/aiplatform/test_endpoints.py
Labels: size: l, api: vertex-ai

#1248 feat: Add Vertex Forecasting E2E test.
  google/cloud/aiplatform/datasets/time_series_dataset.py
  tests/system/aiplatform/test_dataset.py
  tests/system/aiplatform/test_e2e_forecasting.py
Labels: automerge, size: m, api: vertex-ai

#1255 feat: Add hierarchy and window configs to Vertex Forecasting training job
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
Labels: automerge, size: m, api: vertex-ai

#1397 fix: Changed system test to use list_models() correctly
  tests/system/aiplatform/test_model_upload.py
Labels: size: xs, api: vertex-ai

#1253 feat: add holiday regions for vertex forecasting
  google/cloud/aiplatform/training_jobs.py
  tests/unit/aiplatform/test_automl_forecasting_training_jobs.py
Labels: automerge, size: s, api: vertex-ai
