Repository googleapis/python-aiplatform, pull requests merged in 2022-01, with the labels that each got.

#855 fix: Fixed BigQuery datasets that have colon in URI
  google/cloud/aiplatform/datasets/column_names_dataset.py
Labels: cla: yes, api: aiplatform

#812 feat: _TrainingScriptPythonPackager to support folders
  google/cloud/aiplatform/utils/source_utils.py
  tests/unit/aiplatform/test_end_to_end.py
  tests/unit/aiplatform/test_training_jobs.py
Labels: type: feature request, cla: yes, api: aiplatform

#918 feat: enable feature store online serving
  google/cloud/aiplatform/featurestore/entity_type.py
  google/cloud/aiplatform/featurestore/feature.py
  google/cloud/aiplatform/featurestore/featurestore.py
  tests/system/aiplatform/test_featurestore.py
  tests/unit/aiplatform/test_featurestores.py
Labels: automerge

#917 feat: Add XAI SDK integration to TensorFlow models with LIT integration
  google/cloud/aiplatform/explain/lit.py
  setup.py
  tests/unit/aiplatform/test_explain_lit.py
Labels: automerge

#975 fix: Fixed integration test for model.upload
  tests/system/aiplatform/test_model_upload.py
Labels: automerge
